### PR TITLE
fix: improve navbar responsiveness on mobile devices

### LINKED ISSUE #18: [UI] Improve Navbar Responsiveness for Mobile Devices
### 🎯 What’s the suggestion?
Enhance the navbar’s responsiveness for mobile devices to ensure a smoother, more accessible experience.

### 👀 What’s wrong with the current version?
The navbar collapses awkwardly and may not align properly on smaller screens, making it difficult to navigate.

---

> Got a cool idea? We’re all ears.

### PR DESCRIPTION
**Pull request by i-mkarmakar**
# 🚀 Pull Request Overview

## 📄 Description

This PR addresses the issue related to the navbar's responsiveness on mobile devices. It enhances the layout and ensures smoother navigation across different screen sizes.

## 🔗 Related Issue(s)

Closes #18

## 🛠️ Changes Made

* Improved responsive design for the navbar component
* Fixed alignment issues and layout collapse on smaller screens
* Ensured proper spacing and usability on mobile devices

## 🧪 Testing Details

* [x] Ran `npm run dev` without errors
* [x] Manually tested responsiveness on multiple screen sizes
* [ ] Unit tests not applicable for layout changes

## 📸 Screenshots

https://github.com/user-attachments/assets/e58be4b4-f764-4f58-a083-ba62200669db

## 📝 Notes for Reviewers

* This change improves the user experience on mobile devices.
* Let me know if any breakpoint adjustments or style tweaks are needed.

### CODE REVIEW

File: components/header.tsx [hunk 1]
```diff
@@ -62,7 +61,7 @@ export default function Header() {
   const [currentTheme, setCurrentTheme] = useState("system");
 
   const handleSearch = (query: string) => {
-    router.push(`/search?q=${encodeURIComponent(query)}`);
+    router.push(/search?q=${encodeURIComponent(query)});
```
Comment (subh05sus) [inline components/header.tsx:64]: Add quotes here

**Review by subh05sus — CHANGES_REQUESTED** [review]
Add quotes on line no. 64

File: components/header.tsx (hunk 1 above)
Comment (i-mkarmakar) [reply components/header.tsx:64]: Screenshot 2025-05-05 074144
@subh05sus  Now is it ok ?

Comment (subh05sus) [reply components/header.tsx]: yes

**Comment by subh05sus** [comment]
image
it misses quotes in multiple places, kindly recheck all of that in `header.tsx`

**Comment by i-mkarmakar** [comment]
@subh05sus bro, a confussion has arrived that please look in this ss, this is your original code there is no quotes in line no. 65
when I have add quotes here router.push(`/search?q=${encodeURIComponent(`"${query}"`)}`); showing error and also I had not make any changes in this line to fix the logo for mobile screen I made changes in line no. 151,152,541 only.  
Screenshot 2025-05-07 000044

**Comment by subh05sus** [comment]
You don't need to add quotes inside that

**Comment by i-mkarmakar** [comment]
> You don't need to add quotes inside that Check the attached image I sent

but in your original code there is no "" in line no 64 there is ``
